import { db } from './index';
import { venues } from './schema';

async function seedVenues() {
    console.log('🏛️  Seeding conference & event venues...');

    const venueData = [
        {
            name: 'Grand BallRoom',
            slug: 'grand-ballroom',
            description: 'Our magnificent Grand BallRoom is the crown jewel of Olivia Alleppey, offering an unparalleled setting for grand celebrations, corporate galas, and prestigious events. With soaring ceilings adorned with crystal chandeliers and panoramic views, this expansive space combines timeless elegance with state-of-the-art technology. The ballroom can be configured to accommodate intimate gatherings or grand celebrations for up to 500 guests.',
            shortDescription: 'Majestic ballroom perfect for grand celebrations and corporate events',
            venueType: 'ballroom' as const,
            length: '95',
            width: '53',
            height: '13',
            area: 5035,
            capacityTheatre: 500,
            capacityCluster: '180-200',
            capacityClassroom: 130,
            capacityUShape: 60,
            capacityBoardroom: 66,
            capacityBanquet: 350,
            capacityCocktail: 600,
            isDivisible: true,
            hasNaturalLight: true,
            hasAV: true,
            hasWifi: true,
            hasProjector: true,
            hasWhiteboard: false,
            hasStage: true,
            hasDanceFloor: true,
            floor: 1,
            location: 'First Floor',
            isFeatured: true,
            sortOrder: 1,
            isActive: true,
            equipment: ['Professional Sound System', 'LED Stage Lighting', 'Wireless Microphones', 'Projector & Screen', 'Podium', 'Stage'],
            amenities: ['Crystal Chandeliers', 'Climate Control', 'Dedicated Entrance', 'Pre-function Area', 'Bridal Suite', 'VIP Lounge'],
            suitableFor: ['Wedding', 'Corporate Gala', 'Product Launch', 'Award Ceremony', 'Conference', 'Exhibition'],
        },
        {
            name: 'Grand BallRoom 1',
            slug: 'grand-ballroom-1',
            description: 'A versatile section of our Grand BallRoom, perfect for medium-sized events requiring an elegant yet intimate atmosphere. This divisible space maintains all the grandeur of the main ballroom while offering flexibility for events of 100-170 guests.',
            shortDescription: 'Elegant divisible section ideal for medium-sized events',
            venueType: 'ballroom' as const,
            length: '53',
            width: '33',
            height: '13',
            area: 1749,
            capacityTheatre: 170,
            capacityCluster: '66',
            capacityClassroom: 42,
            capacityUShape: 24,
            capacityBoardroom: 24,
            capacityBanquet: 120,
            capacityCocktail: 200,
            isDivisible: false,
            hasNaturalLight: true,
            hasAV: true,
            hasWifi: true,
            hasProjector: true,
            hasWhiteboard: false,
            hasStage: false,
            hasDanceFloor: true,
            floor: 1,
            location: 'First Floor',
            isFeatured: false,
            sortOrder: 2,
            isActive: true,
            equipment: ['Sound System', 'Wireless Microphones', 'Projector & Screen', 'Podium'],
            amenities: ['Crystal Chandeliers', 'Climate Control', 'Natural Light'],
            suitableFor: ['Wedding', 'Corporate Event', 'Seminar', 'Reception'],
        },
        {
            name: 'Grand BallRoom 2',
            slug: 'grand-ballroom-2',
            description: 'The second divisible section of our Grand BallRoom offers the same luxurious ambiance and professional amenities. Ideal for corporate meetings, private celebrations, and social gatherings requiring sophisticated surroundings.',
            shortDescription: 'Sophisticated space for corporate and social events',
            venueType: 'ballroom' as const,
            length: '53',
            width: '35',
            height: '13',
            area: 1855,
            capacityTheatre: 170,
            capacityCluster: '66',
            capacityClassroom: 42,
            capacityUShape: 24,
            capacityBoardroom: 24,
            capacityBanquet: 120,
            capacityCocktail: 200,
            isDivisible: false,
            hasNaturalLight: true,
            hasAV: true,
            hasWifi: true,
            hasProjector: true,
            hasWhiteboard: false,
            hasStage: false,
            hasDanceFloor: true,
            floor: 1,
            location: 'First Floor',
            isFeatured: false,
            sortOrder: 3,
            isActive: true,
            equipment: ['Sound System', 'Wireless Microphones', 'Projector & Screen', 'Podium'],
            amenities: ['Crystal Chandeliers', 'Climate Control', 'Natural Light'],
            suitableFor: ['Wedding', 'Corporate Event', 'Seminar', 'Reception'],
        },
        {
            name: 'Grand BallRoom 3',
            slug: 'grand-ballroom-3',
            description: 'The third section of our divisible Grand BallRoom provides an intimate yet elegant setting. Perfect for executive meetings, private dinners, and boutique events that demand premium surroundings.',
            shortDescription: 'Intimate section perfect for executive gatherings',
            venueType: 'ballroom' as const,
            length: '53',
            width: '27',
            height: '13',
            area: 1431,
            capacityTheatre: 170,
            capacityCluster: '66',
            capacityClassroom: 42,
            capacityUShape: 24,
            capacityBoardroom: 24,
            capacityBanquet: 100,
            capacityCocktail: 150,
            isDivisible: false,
            hasNaturalLight: true,
            hasAV: true,
            hasWifi: true,
            hasProjector: true,
            hasWhiteboard: false,
            hasStage: false,
            hasDanceFloor: false,
            floor: 1,
            location: 'First Floor',
            isFeatured: false,
            sortOrder: 4,
            isActive: true,
            equipment: ['Sound System', 'Wireless Microphones', 'Projector & Screen'],
            amenities: ['Crystal Chandeliers', 'Climate Control', 'Natural Light'],
            suitableFor: ['Corporate Event', 'Private Dinner', 'Seminar', 'Meeting'],
        },
        {
            name: 'Forum 1',
            slug: 'forum-1',
            description: 'A contemporary meeting room designed for productive business sessions. Forum 1 combines modern technology with comfortable furnishings, creating an ideal environment for focused discussions, training sessions, and small conferences.',
            shortDescription: 'Modern meeting room for productive business sessions',
            venueType: 'meeting_room' as const,
            length: '33',
            width: '20',
            height: '9',
            area: 660,
            capacityTheatre: 40,
            capacityCluster: '24',
            capacityClassroom: 28,
            capacityUShape: 18,
            capacityBoardroom: 22,
            capacityBanquet: 30,
            capacityCocktail: 50,
            isDivisible: false,
            hasNaturalLight: true,
            hasAV: true,
            hasWifi: true,
            hasProjector: true,
            hasWhiteboard: true,
            hasStage: false,
            hasDanceFloor: false,
            floor: 2,
            location: 'Second Floor',
            isFeatured: false,
            sortOrder: 5,
            isActive: true,
            equipment: ['LCD Projector', 'Screen', 'Whiteboard', 'Conference Phone', 'Wireless Microphones'],
            amenities: ['Climate Control', 'Natural Light', 'High-Speed WiFi', 'Coffee Station'],
            suitableFor: ['Meeting', 'Training', 'Workshop', 'Presentation', 'Seminar'],
        },
        {
            name: 'Forum 2',
            slug: 'forum-2',
            description: 'Forum 2 offers the same professional amenities as Forum 1, providing a versatile space for various business needs. Perfect for breakout sessions, team meetings, and intimate corporate gatherings.',
            shortDescription: 'Versatile space for meetings and breakout sessions',
            venueType: 'meeting_room' as const,
            length: '33',
            width: '20',
            height: '9',
            area: 660,
            capacityTheatre: 40,
            capacityCluster: '24',
            capacityClassroom: 28,
            capacityUShape: 18,
            capacityBoardroom: 22,
            capacityBanquet: 30,
            capacityCocktail: 50,
            isDivisible: false,
            hasNaturalLight: true,
            hasAV: true,
            hasWifi: true,
            hasProjector: true,
            hasWhiteboard: true,
            hasStage: false,
            hasDanceFloor: false,
            floor: 2,
            location: 'Second Floor',
            isFeatured: false,
            sortOrder: 6,
            isActive: true,
            equipment: ['LCD Projector', 'Screen', 'Whiteboard', 'Conference Phone', 'Wireless Microphones'],
            amenities: ['Climate Control', 'Natural Light', 'High-Speed WiFi', 'Coffee Station'],
            suitableFor: ['Meeting', 'Training', 'Workshop', 'Presentation', 'Seminar'],
        },
        {
            name: 'Forum 3',
            slug: 'forum-3',
            description: 'The largest of our Forum meeting rooms, Forum 3 provides additional space while maintaining the professional atmosphere. Ideal for larger team meetings, training sessions, and small conferences requiring modern facilities.',
            shortDescription: 'Spacious meeting room for larger groups',
            venueType: 'meeting_room' as const,
            length: '42',
            width: '21',
            height: '9',
            area: 882,
            capacityTheatre: 40,
            capacityCluster: '24',
            capacityClassroom: 28,
            capacityUShape: 18,
            capacityBoardroom: 22,
            capacityBanquet: 40,
            capacityCocktail: 60,
            isDivisible: false,
            hasNaturalLight: true,
            hasAV: true,
            hasWifi: true,
            hasProjector: true,
            hasWhiteboard: true,
            hasStage: false,
            hasDanceFloor: false,
            floor: 2,
            location: 'Second Floor',
            isFeatured: false,
            sortOrder: 7,
            isActive: true,
            equipment: ['LCD Projector', 'Screen', 'Whiteboard', 'Conference Phone', 'Wireless Microphones'],
            amenities: ['Climate Control', 'Natural Light', 'High-Speed WiFi', 'Coffee Station'],
            suitableFor: ['Meeting', 'Training', 'Workshop', 'Presentation', 'Seminar'],
        },
        {
            name: 'Poolside',
            slug: 'poolside',
            description: 'Experience the magic of outdoor events at our stunning Poolside venue. Set against the backdrop of Vembanad Lake, this versatile outdoor space is perfect for cocktail receptions, garden parties, and al fresco celebrations. The flexible layout can be customized to suit your event vision, from intimate gatherings to grand celebrations under the stars.',
            shortDescription: 'Enchanting outdoor venue with lake views',
            venueType: 'outdoor' as const,
            length: null,
            width: null,
            height: null,
            area: null,
            capacityTheatre: null,
            capacityCluster: null,
            capacityClassroom: null,
            capacityUShape: null,
            capacityBoardroom: null,
            capacityBanquet: 150,
            capacityCocktail: 250,
            isDivisible: false,
            hasNaturalLight: true,
            hasAV: true,
            hasWifi: true,
            hasProjector: false,
            hasWhiteboard: false,
            hasStage: false,
            hasDanceFloor: true,
            floor: 0,
            location: 'Pool Deck',
            isFeatured: true,
            sortOrder: 8,
            isActive: true,
            equipment: ['Portable Sound System', 'Wireless Microphones', 'Ambient Lighting'],
            amenities: ['Lake Views', 'Pool Access', 'Outdoor Bar', 'Lounge Seating', 'Tropical Gardens'],
            suitableFor: ['Cocktail Reception', 'Garden Party', 'Wedding Reception', 'Corporate Social', 'Product Launch'],
        },
    ];

    try {
        for (const venue of venueData) {
            await db.insert(venues).values(venue);
            console.log(`✓ Added ${venue.name}`);
        }
        console.log('✅ All venues seeded successfully!');
    } catch (error) {
        console.error('❌ Error seeding venues:', error);
        throw error;
    }
}

seedVenues()
    .then(() => {
        console.log('Done!');
        process.exit(0);
    })
    .catch((error) => {
        console.error('Failed:', error);
        process.exit(1);
    });
